### PR TITLE
Update to swagger-ui v5.17.10

### PR DESCRIPTION
**Pull request by sapk**
This PR is the result of updating the submodule reference and resulting files with the `make build` command

### CODE REVIEW

**Review by ubogdan — APPROVED** [review]

**Comment by uvulpos** [comment]
ping

**Comment by gaby** [comment]
@ubogdan @easonlin404 Would it be possible to get this merged or updated to latest and a new release?

**Comment by ubogdan** [comment]
@sapk Thanks for your contribution.
Merged.
 Tagged as v2.0.1

**Comment by gaby** [comment]
@ubogdan Thank you so much! This repo now points to Swagger UI `v5.17.10`, should I make a PR for `v5.17.14`?

**Pull request merged**
