### PR TITLE
Update Swagger UI to 5.18.2

### PR DESCRIPTION
**Pull request by brenth-monad**
Now that openapi --v3.1 is supported in swaggo/swag/v2 there is a need to update the swagger-ui files that also support 3.1.x

### CODE REVIEW

**Review by gaby — APPROVED** [review]
LGTM

**Comment by gaby** [comment]
Ping @ubogdan this package also needs a new release

**Review by ubogdan — APPROVED** [review]
LGTM

**Comment by ubogdan** [comment]
Before merging, please rename the PR title and append the swagger-ui version so we can know the latest one.

**Comment by brenth-monad** [comment]
@ubogdan Thank you for the quick responses. I've updated the PR title with the new version.

**Comment by ubogdan** [comment]
tagged v2.0.2

**Comment by ubogdan** [comment]
@brenth-monad Thanks for your contribution.

**Pull request merged**
