### PR TITLE
feat: go1.16 embed.FS

### PR DESCRIPTION
**Pull request by ubogdan**

### CODE REVIEW

**Comment by ubogdan** [comment]
@sdghchj Please let me know if you have other idea here.

**Comment by sdghchj** [comment]
I known little about this project, so I can only help approve it without a review.

**Review by sdghchj — APPROVED** [review]

**Comment by rhaist** [comment]
Two suggestions:

1.  `actions/setup-go@v2` should be `actions/setup-go@v3`
2.  Add `git submodule update --recursive --remote` to the `build` section of the Makefile to ensure the latest `swagger-ui` version

**Comment by Jictyvoo** [comment]
any updates on merging this? I'm using pprof on a server, and detecting that the package `golang.org/x/net` is consuming a lot of memory, as it uses embed, maybe it can be improved.

**Pull request merged**
